
name: Flutter CICD

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
    - main

jobs:
  build_rubrikrace_android:
    name: Build Rubrik Race Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta' or 'master'
      - run: flutter --version
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
  
  build_rubrikrace_web:
    name: Build Rubrik Web
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build web
    
  build_rubrikrace_windows:
    name: Build Rubrik Windows
    uses: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
  